spring:
   application:
     name: mobilemoneytransactionms
   profiles:
     active: "prod"
     datasource:
       url: jdbc:mysql://localhost:3306/mobilemoneytransactiondb
       username: root
       password: root
     jpa:
       show-sql: true
     sql:
       init:
         mode: always
     config:
       import: "optional:configserver:http://localhost:8071/"

   management:
     endpoints:
       web:
         exposure:
           include: "*"
     endpoint:
       shutdown:
         enabled: true # for graceful shutdown in eureka
     info:
       env:
         enabled: true ;
api:
  microservices:
    bankCharge: 25
    name: "mobilemoneyaccountms"
    baseurl: "http://localhost:8081/"

endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceurl:
      defaultZone: http://localhost:8070/eureka/
#for description in the eureka microservice network.
info:
  app:
    name: "mobilemoneytransactionms"
    description: "Mobile Money"
    version: "1.0.0"
